# The project demonstrates how to use reflection in ADK to iteratively improve an essay about "The Metamorphosis"
# by Franz Kafka.
#
# Architecture:
# - AcademicWriter: Generates the initial draft
# - LiteraryEvaluator: Evaluates the draft and provides feedback
# - AcademicWriter (reflected): Revises the draft based on feedback

import asyncio
import nest_asyncio
import uuid

from google.adk.agents import SequentialAgent, LlmAgent
from google.adk.runners import InMemoryRunner
from google.genai import types


# The first agent generates the initial draft.
academic_writer = LlmAgent(
    name="AcademicWriter",
    description="Generates initial draft content on a given subject.",
    model="gemini-2.5-pro",
    instruction="""
    Role: Academic writer

    Task:
    Write an essay about "The Metamorphosis" by Franz Kafka.
    
    Requirements:
    - Length: 500–700 words
    - Language: English
    - Structure:
      - Introduction with a clear thesis
      - 2–3 body paragraphs
      - Conclusion
    - Required themes:
      - Alienation
      - Identity
      - Family relationships
    - Use Gregor Samsa as the central analytical focus
    
    Quality criteria:
    - Basic coherence
    - Clear and formal tone
    
    Constraints:
    - Do not explain your reasoning
    - Do not evaluate your own writing
    - Do not include meta-commentary or lists
    
    Output:
    Complete essay (initial draft)
    """,
    output_key="draft_text" # The output is saved to this state key.
)


# The second agent evaluates the draft based on specific criteria.
literary_evaluator = LlmAgent(
    name="LiteraryEvaluator",
    description="Evaluates the essay based on specific literary criteria.",
    model="gemini-2.5-pro",
    instruction="""
    Role: Literary evaluator
    
    Task:
    Evaluate the essay generated by AcademicWriter: {draft_text}.
    
    Scoring criteria (0–10 each):
    1. Thesis clarity
    2. Logical coherence
    3. Depth of analysis
    4. Use of textual evidence
    5. Language quality
    
    Process:
    1. Analyze the essay
    2. Identify issues
    3. Assign scores
    4. Decide whether to iterate
    
    Output format:
    
    - Overall summary (max 120 words)
    
    - Issues:
      For each issue:
      - Severity: High / Medium / Low
      - Description
      - Concrete example from the text
    
    - Scores:
      - Thesis: X/10
      - Coherence: X/10
      - Depth: X/10
      - Evidence: X/10
      - Language: X/10
    
    - Decision:
      - ITERATE / FINALIZE
    
    Decision rules:
    - ITERATE if:
      - Any score < 7
      - Any High severity issue exists
    - FINALIZE if:
      - All scores ≥ 8
      - No critical issues
    
    - Improvement instructions (if ITERATE):
      - Prioritized list (max 5 actionable items)
    
    Constraints:
    - Do not rewrite the essay
    - Avoid vague feedback
    """,
    output_key="review_output" # The output is saved to this state key.
)


# The third agent refines the essay based on the evaluation output, focusing on critical issues and providing a revised
# version.
expert_editor = LlmAgent(
    name="ExpertEditor",
    description="Refines the essay based on the evaluation output, focusing on critical issues and providing a revised version.",
    model="gemini-2.5-pro",
    instruction="""
    Role: Expert editor
    
    Task:
    Refine the essay using the evaluation output: {review_output}.
    
    Inputs:
    - Original essay
    - Structured evaluation
    
    Process:
    1. Prioritize High severity issues
    2. Fix logic and evidence gaps
    3. Improve clarity and flow
    4. Rewrite the full essay
    
    Mandatory improvements:
    - Strengthen or clarify the thesis
    - Add concrete textual references (Gregor Samsa, family dynamics)
    - Improve paragraph transitions
    - Remove redundancy
    
    Output format:
    - Full revised essay
    
    - Applied changes:
      - Short list (3–5 items)
      - Explain what was improved and why
    
    Constraints:
    - Do not ignore critical issues
    - Avoid superficial edits
    - Preserve overall coherence
    """,
    output_key="expert_editor" # The output is saved to this state key.
)


# Pipeline that connects the agents in sequence: the output of one agent feeds into the next.
review_pipeline = SequentialAgent(
    name="WriteAndReview_Pipeline",
    sub_agents=[academic_writer, literary_evaluator, expert_editor]
)


async def write_essay(runner: InMemoryRunner, inquiry: str):
    print(f"{'*' * 5} The user needs help with: 'The_Metamorphosis.txt' {'*' * 5}")

    # Create session
    user_id = "user_demo2"
    session_id = str(uuid.uuid4())

    await runner.session_service.create_session(
        app_name=runner.app_name,
        user_id=user_id,
        session_id=session_id
    )

    result = ""

    try:

        async for event in runner.run_async(
                user_id=user_id,
                session_id=session_id,
                new_message=types.Content(
                    role='user',
                    parts=[types.Part(text=inquiry)]
                ),
        ):
            if event.is_final_response() and event.content:
                if getattr(event.content, 'text', None):
                    result = event.content.text
                elif getattr(event.content, 'parts', None):
                    parts = []
                    for part in event.content.parts:
                        if getattr(part, 'text', None):
                            parts.append(part.text)
                        elif getattr(part, 'function_call', None):
                            parts.append(f"[{part.function_call.name}]")
                    result = "".join(parts)
                break

        print(f"The coordinator has resolved the user's inquiry: {result}")
        return result

    except Exception as e:
        print(f"Error: {e}")


async def main():
    runner = InMemoryRunner(review_pipeline)

    # The Metamorphosis by Franz Kafka
    with open("The_Metamorphosis.txt") as f:
        await write_essay(runner, f.read())


if __name__ == "__main__":
    nest_asyncio.apply()
    asyncio.run(main())
